# Copyright 2001-2019 Crytek GmbH / Crytek Group. All rights reserved.
def build(bld):	
	
	bld.CryEditorPlugin(
		target      = 'CryDesigner',
		vs_filter	= 'Sandbox/Plugins',
		file_list   = 'crydesigner.waf_files',
		pch			= 'StdAfx.cpp',
		win_module_extensions = ['toolkit_pro'],
		includes	= [ Path('Code/Sandbox/Plugins/MFCToolsPlugin')	, Path('Code/Sandbox/Plugins')],
		use			= [ 'MFCToolsPlugin' ]
	)
	
