# Copyright 2001-2019 Crytek GmbH / Crytek Group. All rights reserved.

def build(bld):	

	bld.CryEditorPlugin(
		target          = 'EditorCryAudioImplAdx2',
		vs_filter       = 'Sandbox/Plugins/EditorAudioControlsEditor/Impl',
		file_list       = 'editoradx2.waf_files',
		includes        = '../common/'
	)
