# Copyright 2001-2018 Crytek GmbH / Crytek Group. All rights reserved.
	
def build(bld):

	bld.CryEngineModule(
		target      = 'CryScriptSystem',
		vs_filter   = 'CryEngine',		
		file_list   = 'cryscriptsystem.waf_files',

		pch         = 'StdAfx.cpp',
		use_module  = [ 'lua' ],

		win_lib     = [ 'shell32', 'Gdi32', 'wininet', 'Ole32' ],
	)
