# Copyright 2001-2019 Crytek GmbH / Crytek Group. All rights reserved.
from waflib.TaskGen import feature
from waflib.Utils import run_once
import os

def build(bld):

	bld.CryEngineModule(
		target     = 'CryGamePlatform',
		vs_filter  = 'CryPlugins',
		file_list  = 'crygameplatform.waf_files',

		pch        = 'StdAfx.cpp',
						
		includes   = ['../../Interface'],

		module_provides = dict(
			includes = [
				bld.path.make_node('../../Interface').abspath()
			]			
		)
	)
	