# Copyright 2001-2016 Crytek GmbH / Crytek Group. All rights reserved.

def build(bld):
	
	bld.CryEngineModule(
		target		= 'CryAudioImplSDLMixer',
		vs_filter	= 'CryEngine/Audio/Implementations',

		file_list   = 'audioimplsdlmixer.waf_files',
		pch			= 'stdafx.cpp',

		win_module_extensions = ['sdl2', 'sdl_mixer'],
		linux_module_extensions = ['sdl2', 'sdl_mixer'],

		includes = ['../../Common'],
	)
