# Copyright 2001-2018 Crytek GmbH / Crytek Group. All rights reserved.

def build(bld):
	
	bld.CryEngineModule(
		target		= 'CryAudioImplSDLMixer',
		vs_filter	= 'CryEngine/Audio/Implementations',
		file_list   = 'cryaudioimpl.waf_files',
		pch			= 'stdafx.cpp',
		use_module = ['sdl_mixer',
			'timidity',
			'native_midi',
			'flac',
			'libmikmod',
			'libvorbis',
			'libvorbisfile'
		],
		linux_use_module = [ 'libmodplug' ],
		android_use_module = [ 'libmodplug' ],

		module_extensions = ['sdl2'],
		includes = ['../../Common'],
	)
