// Copyright 2001-2019 Crytek GmbH / Crytek Group. All rights reserved.

#include <Cry3DEngine/IRenderNode.h> // <> required for Interfuscator

ENUM_INFO_BEGIN(EERType)
ENUM_ELEM_INFO(, eERType_NotRenderNode)
ENUM_ELEM_INFO(, eERType_Brush)
ENUM_ELEM_INFO(, eERType_Vegetation)
ENUM_ELEM_INFO(, eERType_Light)
ENUM_ELEM_INFO(, eERType_Dummy_5)
ENUM_ELEM_INFO(, eERType_MergedMeshInstance)
ENUM_ELEM_INFO(, eERType_FogVolume)
ENUM_ELEM_INFO(, eERType_Decal)
ENUM_ELEM_INFO(, eERType_ParticleEmitter)
ENUM_ELEM_INFO(, eERType_WaterVolume)
ENUM_ELEM_INFO(, eERType_WaterWave)
ENUM_ELEM_INFO(, eERType_Road)
ENUM_ELEM_INFO(, eERType_DistanceCloud)
ENUM_ELEM_INFO(, eERType_Dummy_4)
ENUM_ELEM_INFO(, eERType_Dummy_0)
ENUM_ELEM_INFO(, eERType_Rope)
ENUM_ELEM_INFO(, eERType_Dummy_3)
ENUM_ELEM_INFO(, eERType_TerrainSector)
ENUM_ELEM_INFO(, eERType_Dummy_2)
ENUM_ELEM_INFO(, eERType_MovableBrush)
ENUM_ELEM_INFO(, eERType_GameEffect)
ENUM_ELEM_INFO(, eERType_BreakableGlass)
ENUM_ELEM_INFO(, eERType_CloudBlocker)
ENUM_ELEM_INFO(, eERType_MergedMesh)
ENUM_ELEM_INFO(, eERType_GeomCache)
ENUM_ELEM_INFO(, eERType_Character)
ENUM_ELEM_INFO(, eERType_TypesNum)
ENUM_INFO_END(EERType)
