# Copyright 2001-2017 Crytek GmbH / Crytek Group. All rights reserved. 

def build(bld):

	bld.CryEngineModule(
		target     = 'CryAISystem',
		vs_filter  = 'CryEngine',		
		file_list  = 'cryaisystem.waf_files',

		pch        = 'StdAfx.cpp',


		use_module    = [ 		
			'CryUQS_Client', 
			'CryUQS_DataSource_XML',
			'CryUQS_StdLib'
		],
	)	
