# Copyright 2001-2019 Crytek GmbH / Crytek Group. All rights reserved.

def build(bld):

	bld.CryEngineModule(
		target     = 'CryAISystem',
		vs_filter  = 'CryEngine',		
		file_list  = 'cryaisystem.waf_files',

		pch        = 'StdAfx.cpp',


		use_module    = [ 		
		],
	)	
