# Copyright 2001-2018 Crytek GmbH / Crytek Group. All rights reserved.

	
def build(bld):

	bld.CryResourceCompilerModule(
		target    = 'CryXML',
		vs_filter = 'RC',		
		file_list = 'cryxml.waf_files',

		use_module = ['expat'],

		defines         = ['CRYXML_EXPORTS', 'CRYTOOLS', '_USE_RTM_VERSION'],
		release_defines = ['NDEBUG'],
		debug_defines   = ['_DEBUG'],

		includes = ['.', Path('Code/Tools'), Path('Code/Tools/RC/ResourceCompiler'), Path('Code/Tools/CryCommonTools')],

		export_definitions = 'CryXML.def'
	)
