# Copyright 2001-2018 Crytek GmbH / Crytek Group. All rights reserved.

def build(bld):

	bld.CryEngineModule( 
		target     = 'CryEntitySystem', 
		vs_filter  = 'CryEngine',		
		file_list  = 'cryentitysystem.waf_files', 

		pch        = 'stdafx.cpp', 
	)		
