# Copyright 2001-2018 Crytek GmbH / Crytek Group. All rights reserved.

def build(bld):

	bld.CryEngineModule(
		target      = 'CryMovie',
		vs_filter   = 'CryEngine',		
		file_list   = 'crymovie.waf_files',	

		pch         = 'StdAfx.cpp',
		includes    = [ '.', Path('Code/CryEngine/CryAction') ]
	)	