# Copyright 2001-2018 Crytek GmbH / Crytek Group. All rights reserved.

def build(bld):	

	bld.CryLauncher( 
		target      = 'WindowsLauncher', 
		vs_filter	= 'Launcher',
		win_file_list   = 'launcher.waf_files', 
		features    = [ 'copy_dbghelp' ],

		lib                  = [ 'Shell32', 'Ws2_32', 'Crypt32', 'oleaut32' ],
		additional_manifests = 'DPIAware.xml',
	)	