# Copyright 2001-2018 Crytek GmbH / Crytek Group. All rights reserved.

def build(bld):	

	posix_defines = [
		'HAVE_DLFCN_H',
		'HAVE_INTTYPES_H',
		'HAVE_MEMORY_H',
		'HAVE_STDINT_H',
		'HAVE_STDLIB_H',
		'HAVE_STRINGS_H',
		'HAVE_STRING_H',
		'HAVE_SYS_STAT_H',
		'HAVE_SYS_TYPES_H',
		'HAVE_UNISTD_H',
		'STDC_HEADERS',
	]

	bld.CryEngineStaticModule( 
		target    = 'libogg', 
		vs_filter = 'Libs/Audio',
		file_list = 'libogg.waf_files',
		exclude_from_static_code_analyzer = True,
		
		includes = [ Path('Code/SDKs/libogg/include')],	

		linux_defines = posix_defines,
		android_defines = posix_defines,

		# No warnings in 3rdParty code, we can't fix them anyway
		win_cflags = [ '/W0' ],
		linux_cflags = [ '-w' ],

		module_provides = dict(
			includes = [ Path('Code/SDKs/libogg/include') ]
		)
	)
