# Copyright 2001-2016 Crytek GmbH / Crytek Group. All rights reserved.

def build(bld):	

	bld.CryEngineStaticModule( 
		target     = 'yasli', 
		vs_filter  = 'Libs',
		file_list  = 'yasli.waf_files',
		exclude_from_static_code_analyzer = True,
		use_module = [ ],
		includes   = [
			Path('Code/Libs/yasli'),
			Path('Code/SDKs/yasli'),
		],
		module_provides = dict(
			includes = [
				Path('Code/Libs/yasli'),
				Path('Code/SDKs/yasli'),
			],
		),
		defines    = [],
	)
