# Copyright 2001-2016 Crytek GmbH / Crytek Group. All rights reserved.

def build(bld):
	bld.CryFileContainer(
		target		= 'CryAudioCommon',
		vs_filter	= 'CryEngine/Audio',
		file_list	= 'audiocommon.waf_files',
	)
