# Copyright 2001-2018 Crytek GmbH / Crytek Group. All rights reserved.

def build(bld):	

	bld.CryPlugin(
		target          = 'EditorCryAudioImplFmod',
		vs_filter       = 'Sandbox/Plugins/EditorAudioControlsEditor/Impl',
		file_list       = 'editorfmod.waf_files',
		includes        = '../common/'
	)
