# Copyright 2001-2016 Crytek GmbH / Crytek Group. All rights reserved.
def build(bld):	
	
	bld.CryPlugin(
		target      = 'FacialEditorPlugin',
		vs_filter	= 'Sandbox/Plugins',
		file_list   = 'FacialEditorPlugin.waf_files',
		pch			= 'StdAfx.cpp',
		use			= [ 'MFCToolsPlugin' ],
		includes	= [ Path('Code/Sandbox/Plugins/MFCToolsPlugin')	]
	)