#############################################################################
## Crytek Source File
## Copyright (C) 2013, Crytek Studios
##
## Creator: Christian Werle
## Date: Jan 06, 2016
## Description: WAF  based build system
#############################################################################

def build(bld):

	bld.CryFileContainer(
		target        = 'CryUQS_Client',
		vs_filter     = 'CryPlugins/CryUQS',
		file_list     = 'uqs_client.waf_files'
	)