# Copyright 2001-2019 Crytek GmbH / Crytek Group. All rights reserved.

def build(bld):	
	bld.CryEditorPlugin(
		target          = 'EditorAudioControlsEditor',
		vs_filter       = 'Sandbox/Plugins/EditorAudioControlsEditor',		
		file_list       = 'editoraudiocontrolseditor.waf_files',
		pch             = 'StdAfx.cpp',		
		includes	    = [ 'common', Path('Code/CryEngine/CryAction') ]
	)

	bld.recurse_subdirs(mandatory=False)
