// Copyright 2001-2018 Crytek GmbH / Crytek Group. All rights reserved.

#include "ZipFileFormat.h"

STRUCT_INFO_BEGIN(ZipFile::CDREnd)
VAR_INFO(lSignature)
VAR_INFO(nDisk)
VAR_INFO(nCDRStartDisk)
VAR_INFO(numEntriesOnDisk)
VAR_INFO(numEntriesTotal)
VAR_INFO(lCDRSize)
VAR_INFO(lCDROffset)
VAR_INFO(nCommentLength)
STRUCT_INFO_END(ZipFile::CDREnd)

STRUCT_INFO_BEGIN(ZipFile::DataDescriptor)
VAR_INFO(lCRC32)
VAR_INFO(lSizeCompressed)
VAR_INFO(lSizeUncompressed)
STRUCT_INFO_END(ZipFile::DataDescriptor)

STRUCT_INFO_BEGIN(ZipFile::CDRFileHeader)
VAR_INFO(lSignature)
VAR_INFO(nVersionMadeBy)
VAR_INFO(nVersionNeeded)
VAR_INFO(nFlags)
VAR_INFO(nMethod)
VAR_INFO(nLastModTime)
VAR_INFO(nLastModDate)
VAR_INFO(desc)
VAR_INFO(nFileNameLength)
VAR_INFO(nExtraFieldLength)
VAR_INFO(nFileCommentLength)
VAR_INFO(nDiskNumberStart)
VAR_INFO(nAttrInternal)
VAR_INFO(lAttrExternal)
VAR_INFO(lLocalHeaderOffset)
STRUCT_INFO_END(ZipFile::CDRFileHeader)

STRUCT_INFO_BEGIN(ZipFile::LocalFileHeader)
VAR_INFO(lSignature)
VAR_INFO(nVersionNeeded)
VAR_INFO(nFlags)
VAR_INFO(nMethod)
VAR_INFO(nLastModTime)
VAR_INFO(nLastModDate)
VAR_INFO(desc)
VAR_INFO(nFileNameLength)
VAR_INFO(nExtraFieldLength)
STRUCT_INFO_END(ZipFile::LocalFileHeader)
