# Copyright 2001-2018 Crytek GmbH / Crytek Group. All rights reserved.

def build(bld):	

	bld.CryEngineStaticModule( 
		target    = 'lzma', 
		vs_filter = 'Libs',
		file_list = 'lzma.waf_files',
		exclude_from_static_code_analyzer = True,

		module_provides = dict(
			includes = [ Path('Code/SDKs'), ],
		)
)
