# Copyright 2001-2018 Crytek GmbH / Crytek Group. All rights reserved.

def build(bld):	

	bld.CryPlugin(
		target          = 'EditorCryAudioImplWwise',
		vs_filter       = 'Sandbox/Plugins/EditorAudioControlsEditor/Impl',
		file_list       = 'editorwwise.waf_files',
		includes        = ['../common/', 'GeneratedFiles'],
		output_sub_folder = "Audio"
	)
