# Copyright 2001-2018 Crytek GmbH / Crytek Group. All rights reserved.

def build(bld) :

	bld.CryEngineModule(
	  target = 'CryUserAnalytics',
	  vs_filter = 'CryPlugins',
	  file_list = 'cryuseranalytics.waf_files',

	  win_use_module = ['curl'],
	  win_lib        = ['Ole32', 'Shell32'],

	  pch = 'StdAfx.cpp'
	  )
