# Copyright 2001-2018 Crytek GmbH / Crytek Group. All rights reserved.

def build(bld):

	bld.CryFileContainer( 
		target     = 'EditorInterface', 
		vs_filter  = 'Sandbox',
		file_list  = ['editorinterface.waf_files'],
	)	

