# Check if sdks script is available
set(CAN_DOWNLOAD_SDKS OFF)
if(EXISTS "${CMAKE_SOURCE_DIR}/download_sdks.exe")
	set(CAN_DOWNLOAD_SDKS ON)
endif ()

set(NEEDS_SDKS ON)
if(EXISTS "${CMAKE_SOURCE_DIR}/Code/SDKs")
	set(NEEDS_SDKS OFF)
endif ()

if (CAN_DOWNLOAD_SDKS AND NEEDS_SDKS)
	# Update bootstrap
	message(STATUS "Downloading SDKs...")
	if(CMAKE_HOST_SYSTEM_NAME MATCHES "Windows")
		execute_process(COMMAND "${CMAKE_SOURCE_DIR}/download_sdks.exe"        WORKING_DIRECTORY "${CMAKE_SOURCE_DIR}" RESULT_VARIABLE bootstrapRes)
	elseif(CMAKE_HOST_SYSTEM_NAME MATCHES "Linux")                                               
		execute_process(COMMAND python3 "${CMAKE_SOURCE_DIR}/download_sdks.py" WORKING_DIRECTORY "${CMAKE_SOURCE_DIR}" RESULT_VARIABLE bootstrapRes)
	elseif(CMAKE_HOST_SYSTEM_NAME MATCHES "Darwin")                                              
		execute_process(COMMAND python3 "${CMAKE_SOURCE_DIR}/download_sdks.py" WORKING_DIRECTORY "${CMAKE_SOURCE_DIR}" RESULT_VARIABLE bootstrapRes)
	else()
		message(FATAL_ERROR "Unknown host, unable to locate download_sdks executable.")
	endif()
	if(bootstrapRes EQUAL 0)
		message("Downloading SDKs completed.")
	else()
		message(FATAL_ERROR "Downloading SDKs failed, aborting.")
	endif()
endif()
