# Copyright 2001-2016 Crytek GmbH / Crytek Group. All rights reserved.
def build(bld):	
	
	bld.CryPlugin(
		target      = 'SamplePlugin',
		vs_filter	= 'Sandbox/Plugins',
		file_list   = 'SamplePlugin.waf_files',
		pch			= 'StdAfx.cpp'
	)