# Copyright 2001-2016 Crytek GmbH / Crytek Group. All rights reserved.

def build(bld):
	bld.CryEngineStaticModule(
		target     = 'CryParticleSystem',
		vs_filter  = 'CryEngine',
		file_list  = 'particlesystem.waf_files',
		pch        = 'StdAfx.cpp',
		includes = [
			'.',
			'..',	# allowing #include "ParticleSystem/ParticleFeature.h" in feature folder
			Path('Code/CryEngine/Cry3DEngine'),
		]
	)