# Copyright 2001-2018 Crytek GmbH / Crytek Group. All rights reserved.

def build(bld):
	bld.CryPlugin(
		target = 'MonoDevelopPlugin',
		vs_filter = 'Sandbox/Plugins',
		file_list = 'monodevelop_plugin.waf_files',
		pch = 'StdAfx.cpp',
		module_extensions = ['toolkit_pro'],
		includes = [ '.', '..', Path('Code/CryEngine/CryAction') ],
		use = [ 'Editor', 'EditorCommon' ]
	)

