// Copyright 2001-2019 Crytek GmbH / Crytek Group. All rights reserved.

#pragma once

constexpr CVarWhitelistEntry g_cvarWhitelist[] =
{
	"sys_project",
	"sys_game_folder",

	"map",
	"i_mouse_smooth",
	"i_mouse_accel",
	"i_mouse_accel_max",
	"cl_sensitivity",
	"pl_movement.power_sprint_targetFov",
	"cl_fov",
	"hud_canvas_width_adjustment",
	"r_DrawNearFoV",
	"g_skipIntro",
	"hud_psychoPsycho",
	"hud_hide",
	"disconnect",

	"hud_bobHud",
	"e_CoverageBufferReproj",
	"e_LodRatio",
	"e_ViewDistRatio",
	"e_ViewDistRatioVegetation",
	"e_ViewDistRatioDetail",
	"e_MergedMeshesInstanceDist",
	"e_MergedMeshesViewDistRatio",
	"e_ParticlesObjectCollisions",
	"e_ParticlesMotionBlur",
	"e_ParticlesForceSoftParticles",
	"e_Tessellation",
	"e_TessellationMaxDistance",
	"r_TessellationTriangleSize",
	"r_SilhouettePOM",
	"e_GI",
	"e_GICache",
	"e_GIIterations",
	"e_ShadowsPoolSize",
	"e_ShadowsMaxTexRes",
	"r_FogShadows",
	"r_FogShadowsWater",
	"e_ParticlesShadows",
	"e_ShadowsTessellateCascades",
	"e_ShadowsResScale",
	"e_GsmCache",
	"r_WaterTessellationHW",
	"r_DepthOfField",
	"r_MotionBlur",
	"r_MotionBlurShutterSpeed",
	"g_radialBlur",
	"cl_zoomToggle",
	"r_TexMinAnisotropy",
	"r_TexMaxAnisotropy",
	"r_TexturesStreamPoolSize",
	"cl_crouchToggle",
	"r_ColorGrading",
	"r_SSAO",
	"r_SSDO",
	"r_SSReflections",
	"r_VSync",
	"r_DisplayInfo",
	"r_displayinfoTargetFPS",
	"r_ChromaticAberration",
	"r_HDRChromaShift",
	"r_HDRGrainAmount",
	"r_GrainEnableExposureThreshold",
	"r_HDRBloomRatio",
	"r_HDRBrightLevel",
	"r_Sharpening",
	"r_Gamma",
	"r_GetScreenShot",
	"r_FullscreenWindow",
	"r_Fullscreen",
	"r_width",
	"r_height",
	"r_MultiGPU",
	"r_overrideDXGIOutput",
	"r_overrideDXGIAdapter",
	"r_FullscreenPreemption",
	"r_buffer_sli_workaround",
	"r_DeferredShadingAmbientSClear",
	"g_useHitSoundFeedback",
	"sys_MaxFps",
	"g_language",

	"sys_spec_ObjectDetail",
	"sys_spec_Shading",
	"sys_spec_VolumetricEffects",
	"sys_spec_Shadows",
	"sys_spec_Texture",
	"sys_spec_Physics",
	"sys_spec_PostProcessing",
	"sys_spec_Particles",
	"sys_spec_Sound",
	"sys_spec_Water",
	"sys_spec_GameEffects",
	"sys_spec_Light",

	"g_dedi_email",
	"g_dedi_password",

	"root",
	"logfile",
	"ResetProfile",
	"nodlc",

	"rcon_connect",
	"rcon_disconnect",
	"rcon_command",

	"quit",
	"votekick",
	"vote",

	"net_blaze_voip_enable",

	"sys_vr_support",

#if defined(DEDICATED_SERVER)
	"ban",
	"ban_remove",
	"ban_status",
	"ban_timeout",
	"kick",
	"startPlaylist",
	"status",
	"gl_map",
	"gl_gamerules",
	"sv_gamerules",
	"sv_password",
	"maxplayers",
	"sv_servername",

	"sv_bind",
	"g_scoreLimit",
	"g_timelimit",
	"g_minplayerlimit",
	"g_autoReviveTime",
	"g_numLives",
	"g_maxHealthMultiplier",
	"g_mpRegenerationRate",
	"g_friendlyfireratio",
	"g_mpHeadshotsOnly",
	"g_mpNoVTOL",
	"g_mpNoEnvironmentalWeapons",
	"g_allowCustomLoadouts",
	"g_allowFatalityBonus",
	"g_modevarivar_proHud",
	"g_modevarivar_disableKillCam",
	"g_modevarivar_disableSpectatorCam",
	"g_multiplayerDefault",
	"g_allowExplosives",
	"g_forceWeapon",
	"g_allowWeaponCustomisation",
	"g_infiniteCloak",
	"g_infiniteAmmo",
	"g_forceHeavyWeapon",
	"g_forceLoadoutPackage",


	"g_autoAssignTeams",
	"gl_initialTime",
	"gl_time",
	"g_gameRules_startTimerLength",
	"sv_maxPlayers",
	"g_switchTeamAllowed",
	"g_switchTeamRequiredPlayerDifference",
	"g_switchTeamUnbalancedWarningDifference",
	"g_switchTeamUnbalancedWarningTimer",

	"http_startserver",
	"http_stopserver",
	"http_password",

	"rcon_startserver",
	"rcon_stopserver",
	"rcon_password",

	"gl_StartGame",
	"g_messageOfTheDay",
	"g_serverImageUrl",

	"log_Verbosity",
	"log_WriteToFile",
	"log_WriteToFileVerbosity",
	"log_IncludeTime",
	"log_tick",
	"net_log",

	"g_pinglimit",
	"g_pingLimitTimer",

	"g_tk_punish",
	"g_tk_punish_limit",
	"g_idleKickTime",

	"net_reserved_slot_system",
	"net_add_reserved_slot",
	"net_remove_reserved_slot",
	"net_list_reserved_slot",

	"sv_votingCooldown",
	"sv_votingRatio",
	"sv_votingTimeout",
	"sv_votingEnable",
	"sv_votingBanTime",

	"g_dataRefreshFrequency",
	"g_quitOnNewDataFound",
	"g_quitNumRoundsWarning",
	"g_allowedDataPatchFailCount",
	"g_shutdownMessageRepeatTime",
	"g_shutdownMessage",
	"g_patchPakDediServerMustPatch",

	"g_server_region",

	"net_log_dirtysock",
#endif

	"sys_user_folder",
	"sys_screensaver_allowed",
	"sys_UncachedStreamReads",
};
#define CVAR_WHITELIST_ENTRIES g_cvarWhitelist
