# Copyright 2001-2018 Crytek GmbH / Crytek Group. All rights reserved.

def build(bld):

	bld.CryEngineModule(
		target     = 'CryDynamicResponseSystem',
		vs_filter  = 'CryEngine',
		file_list  = 'crydynamicresponsesystem.waf_files',
		pch        = 'stdafx.cpp',
		includes = [
			'.', 
			Path('Code/CryEngine/CryCommon'),
			Path('Code/CryEngine/CrySchematyc/Core/Interface'),
			Path('Code/CryEngine/CrySchematyc/STDEnv/Interface')
		]
	)
