# Copyright 2001-2016 Crytek GmbH / Crytek Group. All rights reserved.

def build(bld):

	bld.CryEngineModule(
		target     = 'CryDynamicResponseSystem',
		vs_filter  = 'CryEngine',
		file_list  = 'crydynamicresponsesystem.waf_files',
		pch        = 'stdafx.cpp'
	)
