# Copyright 2001-2018 Crytek GmbH / Crytek Group. All rights reserved.

def build(bld) :

	bld.CryEngineModule(
	  target = 'CryOculusVR',
	  vs_filter = 'CryPlugins',
	  file_list = 'cryoculusvr.waf_files',

	  pch = 'StdAfx.cpp',
	  
	  includes  = Path('Code/SDKs/OculusSDK/LibOVR/Include'),
	  
	  win_use_module = [ 'oculus' ]
	  )

	  