/* Generated automatically by H5make_libsettings -- do not edit */



/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * Copyright by The HDF Group.                                               *
 * Copyright by the Board of Trustees of the University of Illinois.         *
 * All rights reserved.                                                      *
 *                                                                           *
 * This file is part of HDF5.  The full HDF5 copyright notice, including     *
 * terms governing use, modification, and redistribution, is contained in    *
 * the COPYING file, which can be found at the root of the source code       *
 * distribution tree, or in https://support.hdfgroup.org/ftp/HDF5/releases.  *
 * If you do not have access to either file, you may request a copy from     *
 * help@hdfgroup.org.                                                        *
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 *
 * Created:		Nov  3, 2017
 *			davidka <davidka@FRLP1DAVIDKA>
 *
 * Purpose:		This machine-generated source code contains
 *			information about the library build configuration
 *
 * Modifications:
 *
 *	DO NOT MAKE MODIFICATIONS TO THIS FILE!
 *	It was generated by code in `H5make_libsettings.c'.
 *
 *-------------------------------------------------------------------------
 */

char H5libhdf5_settings[]=
	"      SUMMARY OF THE HDF5 CONFIGURATION\n"
	"      =================================\n"
	"\n"
	"General Information:\n"
	"-------------------\n"
	"                   HDF5 Version: 1.8.19\n"
	"                  Configured on: 2017-11-03\n"
	"                  Configured by: Unix Makefiles\n"
	"                 Configure mode: CMAKE 3.9.1\n"
	"                    Host system: Linux-4.13.0-16-generic\n"
	"              Uname information: Linux\n"
	"                       Byte sex: little-endian\n"
	"                      Libraries: \n"
	"             Installation point: /data/p4/FRLP1DAVIDKA_bootstrap/Alembic/CMake-hdf5-1.8.19/HDF_Group/HDF5/1.8.19\n"
	"\n"
	"Compiling Options:\n"
	"------------------\n"
	"               Compilation Mode: Release\n"
	"                     C Compiler: /usr/bin/cc\n"
	"                         CFLAGS:   -std=c99 -fstdarg-opt -Wundef -Wshadow -Wpointer-arith -Wbad-function-cast -Wcast-align -Wwrite-strings -Wconversion -Waggregate-return -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wredundant-decls -Wnested-externs -Wno-unused-parameter -Wno-inline -Wno-aggregate-return -Wall -Wextra -pedantic  -Wfloat-equal -Wmissing-format-attribute -Wpacked -Wdisabled-optimization -Wno-missing-noreturn -Wendif-labels -Wdeclaration-after-statement -Wold-style-definition -Winvalid-pch  -Wvariadic-macros -Winit-self -Wmissing-include-dirs -Wswitch-default -Wswitch-enum -Wunused-macros -Wc++-compat -Wno-strict-overflow -Wlogical-op -Wlarger-than=2048 -Wvla -Wsync-nand -Wframe-larger-than=16384 -Wpacked-bitfield-compat -Wjump-misses-init -Wunsuffixed-float-constants -Wdouble-promotion -Wtrampolines -Wno-suggest-attribute=const -Wunreachable-code -Wstack-usage=8192 -Wvector-operation-performance -Wno-suggest-attribute=pure -Wno-suggest-attribute=noreturn -Wno-suggest-attribute=format -Wdate-time -Wopenmp-simd -fmessage-length=0\n"
	"                      H5_CFLAGS: \n"
	"                      AM_CFLAGS: \n"
	"                       CPPFLAGS: \n"
	"                    H5_CPPFLAGS: \n"
	"                    AM_CPPFLAGS: \n"
	"               Shared C Library: NO\n"
	"               Static C Library: YES\n"
	"  Statically Linked Executables: OFF\n"
	"                        LDFLAGS: \n"
	"                     AM_LDFLAGS: \n"
	"                Extra libraries: m;dl;zlib-static;szip-static\n"
	"                       Archiver: /usr/bin/ar\n"
	"                         Ranlib: /usr/bin/ranlib\n"
	"              Debugged Packages: \n"
	"                    API Tracing: OFF\n"
	"\n"
	"Languages:\n"
	"----------\n"
	"                        Fortran: OFF\n"
	"               Fortran Compiler: \n"
	"          Fortran 2003 Compiler: OFF\n"
	"                  Fortran Flags: \n"
	"               H5 Fortran Flags: \n"
	"               AM Fortran Flags: \n"
	"         Shared Fortran Library: NO\n"
	"         Static Fortran Library: YES\n"
	"\n"
	"                            C++: ON\n"
	"                   C++ Compiler: /usr/bin/c++\n"
	"                      C++ Flags:   -fstdarg-opt -fmessage-length=0\n"
	"                   H5 C++ Flags: \n"
	"                   AM C++ Flags: \n"
	"             Shared C++ Library: NO\n"
	"             Static C++ Library: YES\n"
	"\n"
	"Features:\n"
	"---------\n"
	"                  Parallel HDF5: OFF\n"
	"             High Level library: ON\n"
	"                   Threadsafety: OFF\n"
	"            Default API Mapping: v18\n"
	" With Deprecated Public Symbols: ON\n"
	"         I/O filters (external):  DEFLATE DECODE ENCODE\n"
	"                            MPE: \n"
	"                     Direct VFD: \n"
	"                        dmalloc: \n"
	"Clear file buffers before write: ON\n"
	"           Using memory checker: OFF\n"
	"         Function Stack Tracing: OFF\n"
	"      Strict File Format Checks: OFF\n"
	"   Optimization Instrumentation: \n"
;

