# Copyright 2001-2018 Crytek GmbH / Crytek Group. All rights reserved.

def build(bld):
	# No warnings in 3rdParty code, we can't fix them anyway
	common_win_cflags = [ '/W0', ]
	common_linux_cflags = ['-w']
	common_android_cflags = ['-w']

	common_defines = [
		'OGG_MUSIC',
		'MID_MUSIC',
		'FLAC_MUSIC',
		'MOD_MUSIC',
		'MODPLUG_MUSIC',
		'MODPLUG_HEADER="modplug.h"',
		'USE_TIMIDITY_MIDI',
		'USE_NATIVE_MIDI',
	]
	
	common_win_defines = [
		'WAV_MUSIC',
		'MP3_MUSIC',
		'MODPLUG_DYNAMIC="libmodplug-1.dll"',
		'MP3_DYNAMIC="smpeg2.dll"'
	]

	bld.CryEngineStaticModule( 
		target    = 'sdl_mixer', 
		vs_filter = 'Libs/Audio',
		file_list = 'SDL_mixer.waf_files',
		exclude_from_static_code_analyzer = True,

		output_file_name = "SDL2_mixer",

		includes = [
			Path('Code/SDKs/SDL_mixer'),
			Path('Code/SDKs/libmodplug/src'),
			Path('Code/SDKs/libmodplug/src/libmodplug')],
		win_includes = [
			Path('Code/SDKs/SDL_mixer/VisualC/external/include')],

		use_module = ['timidity',
			'native_midi',
			'flac',
			'libogg',
			'libmikmod',
			'libvorbis',
			'libvorbisfile'
			],
		linux_use_module = [ 'libmodplug' ],
		module_extensions = ['sdl2'],

		win_lib = ['Winmm'],

		defines = common_defines,
		win_defines = common_win_defines,
		win_cflags  = common_win_cflags,
		linux_cflags = common_linux_cflags,
		android_cflags = common_android_cflags,

		module_provides = dict(
			includes = [Path('Code/SDKs/SDL_mixer')],
			win_lib = ['Winmm']
		)
	)

	bld.CryEngineStaticModule( 
		target    = 'timidity', 
		vs_filter = 'Libs/Audio',
		file_list = 'timidity.waf_files',
		exclude_from_static_code_analyzer = True,
		includes = [Path('Code/SDKs/SDL_mixer/timidity')],

		module_extensions = ['sdl2'],

		win_cflags  = common_win_cflags,

		module_provides = dict(
			includes = [Path('Code/SDKs/SDL_mixer/timidity')],
		)
	)

	bld.CryEngineStaticModule( 
		target    = 'native_midi', 
		vs_filter = 'Libs/Audio',
		file_list = 'native_midi.waf_files',
		exclude_from_static_code_analyzer = True,
		includes = [Path('Code/SDKs/SDL_mixer/native_midi')],

		module_extensions = ['sdl2'],

		win_cflags  = common_win_cflags,

		module_provides = dict(
			includes = [Path('Code/SDKs/SDL_mixer/native_midi')],
		)	
	)
