# Copyright 2001-2018 Crytek GmbH / Crytek Group. All rights reserved.
	
def build(bld):
	bld.CryEngineModule(
		features                = 'swig',
		target                  = 'CryMonoBridge',
		vs_filter               = 'CryEngine',
		file_list               = 'crymonobridge.waf_files',
		pch                     = 'StdAfx.cpp',
		
		cxxflags                = [ '/EHsc', '/bigobj' ],
		
		includes                = [ Path('Code/CryEngine/CryAction') ],
		win_lib                 = [ 'Shell32' ],
		
		win_module_extensions   = [ "mono" ]
	)