# Copyright 2001-2018 Crytek GmbH / Crytek Group. All rights reserved.

SUBFOLDERS =	[
	'ResourceCompiler',
	'ResourceCompilerABC',
	'ResourceCompilerImage',
	'ResourceCompilerPC',
	'ResourceCompilerXML',
	]

def build(bld):
	# Recursive into all sub projects
	bld.recurse(SUBFOLDERS)
