# Copyright 2001-2019 Crytek GmbH / Crytek Group. All rights reserved.

def build(bld):
	
	bld.CryFileContainer(
		target      = 'HWScripts', 
		vs_filter   = 'CryEngine/Shaders',
		file_list   = 'hwscripts.waf_files'
	)	