# Copyright 2001-2018 Crytek GmbH / Crytek Group. All rights reserved.
def build(bld):	

	bld.CryFileContainer(
		target		= 'EditorAudioControlsEditorCommon',
		vs_filter	= 'Sandbox/Plugins/EditorAudioControlsEditor',
		file_list	= 'editoraudiocontrolseditorcommon.waf_files',
	)
