# Copyright 2001-2018 Crytek GmbH / Crytek Group. All rights reserved.

def build(bld):	

	bld.CryPlugin(
		target      = 'EditorAnimation',
		vs_filter   = 'Sandbox/Plugins',
		file_list   = 'editoranimation.waf_files',		
		pch			= 'stdafx.cpp',	
		includes    = ['..',
				Path('Code/Sandbox/EditorQt/Include'),
				Path('Code/Sandbox/EditorQt')
				],
		use			= [ 'Sandbox' ],
		libpath     = Path('Code/Sandbox/SDKs/OpenCollada/COLLADAStreamWriter/lib/win/Win32/Release'),
	)

