# Copyright 2001-2019 Crytek GmbH / Crytek Group. All rights reserved.

def build(bld):	

	bld.CryEditorPlugin(
		target      = 'EditorAnimation',
		vs_filter   = 'Sandbox/Plugins',
		file_list   = 'editoranimation.waf_files',		
		pch			= 'stdafx.cpp',
		libpath     = Path('Code/Sandbox/SDKs/OpenCollada/COLLADAStreamWriter/lib/win/Win32/Release')
	)

