//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Resource.rc
//
#define IDB_SCHEMATYC_BROWSER_ICONS     102
#define IDR_SCHEMATYC_TOOLBAR           104
#define IDR_SCHEMATYC_MENU              110
#define IDD_SCHEMATYC_ADD_STATE         314
#define IDD_SCHEMATYC_QUICK_SEARCH      317
#define IDD_SCHEMATYC_ADD_GRAPH         321
#define IDD_SCHEMATYC_ADD_ABSTRACT_INTERFACE 328
#define IDD_SCHEMATYC_ADD_ABSTRACT_INTERFACE_IMPLEMENTATION 328
#define IDD_SCHEMATYC_PROPERTY_TREE     335
#define IDD_SCHEMATYC_ADD_CONTAINER     336
#define IDD_SCHEMATYC_NAME              340
#define IDC_SCHEMATYC_STATE_NAME        1002
#define IDC_SCHEMATYC_QUICK_SEARCH_FILTER 1010
#define IDC_SCHEMATYC_GRAPH_NAME        1023
#define IDC_SCHEMATYC_GRAPH_FILTER      1024
#define IDC_SCHEMATYC_QUICK_SEARCH_TREE 1029
#define IDD_SCHEMATYC_ABSTRACT_INTERFACES 1040
#define IDD_SCHEMATYC_ABSTRACT_INTERFACE_DESCRIPTION 1041
#define IDD_SCHEMATYC_GRAPH_CONTEXT     1057
#define IDC_SCHEMATYC_PROPERTY_TREE     1064
#define IDC_SCHEMATYC_CONTAINER_TYPES   1065
#define IDC_SCHEMATYC_CONTAINER_NAME    1066
#define IDC_SCHEMATYC_STATE_PARTNER     1071
#define IDC_SCHEMATYC_NAME              1076
#define IDC_SCHEMATYC_QUICK_SEARCH_DESCRIPTION 1077
#define IDC_SCHEMATYC_QUICK_SEARCH_VIEW_WIKI 1078
#define ID_SCHEMATYC_SAVE               33630
#define ID_SCHEMATYC_REFRESH_ENV        40002
#define ID_SCHEMATYC_VIEW_BROWSER       40010
#define ID_SCHEMATYC_VIEW_ENV_BROWSER   40011
#define ID_SCHEMATYC_VIEW_DETAIL        40013
#define ID_SCHEMATYC_VIEW_GRAPH         40014
#define ID_SCHEMATYC_VIEW_COMPILER_OUTPUT 40016
#define ID_SCHEMATYC_VIEW_VIEWPORT      40017
#define ID_SCHEMATYC_VIEW_LOG_OUTPUT_A  40032
#define ID_SCHEMATYC_VIEW_LOG_OUTPUT_C  40033
#define ID_SCHEMATYC_VIEW_LOG_OUTPUT_D  40034
#define ID_SCHEMATYC_VIEW_LOG_OUTPUT_B  40035
#define ID_SCHEMATYC_TOOLS_CONFIGURE_LOG_OUTPUT_A 40040
#define ID_SCHEMATYC_TOOLS_CONFIGURE_LOG_OUTPUT_B 40041
#define ID_SCHEMATYC_TOOLS_CONFIGURE_LOG_OUTPUT_C 40042
#define ID_SCHEMATYC_TOOLS_CONFIGURE_LOG_OUTPUT_D 40043
#define ID_SCHEMATYC_DEBUG_SELECTED_ENTITY 40045
#define ID_SCHEMATYC_WORLD_DEBUG_SHOW_STATES 40054
#define ID_SCHEMATYC_WORLD_DEBUG_SHOW_VARIABLES 40062
#define ID_SCHEMATYC_WORLD_DEBUG_SHOW_TIMERS 40063
#define ID_SCHEMATYC_WORLD_DEBUG_SHOW_ACTIONS 40064
#define ID_SCHEMATYC_ENTITY_DEBUG_SHOW_STATES 40065
#define ID_SCHEMATYC_ENTITY_DEBUG_SHOW_VARIABLES 40067
#define ID_SCHEMATYC_ENTITY_DEBUG_SHOW_ACTIONS 40068
#define ID_SCHEMATYC_ENTITY_DEBUG_SHOW_TIMERS 40069
#define ID_SCHEMATYC_ENTITY_DEBUG_SHOW_SIGNAL_HISTORY 40072
#define ID_SCHEMATYC_WORLD_DEBUG_SHOW_SIGNAL_HISTORY 40073
#define ID_SCHEMATYC_ENTITY_DEBUG_SHOW_CONTAINERS 40075
#define ID_SCHEMATYC_WORLD_DEBUG_SHOW_CONTAINERS 40077
#define ID_SCHEMATYC_HELP_VIEW_WIKI     40078
#define ID_SCHEMATYC_HELP_VIEW_SHORTCUT_KEYS 40079
#define ID_Menu                         40080
#define ID_SCHEMATYC_VIEW_NEW_LOG_OUTPUT 40081
#define ID_FILE_SAVESETTINGS            40082
#define ID_SCHEMATYC_SAVE_SETTINGS      40083
#define ID_SCHEMATYC_VIEW_PREVIEW       40084
#define ID_SCHEMATYC_GO_TO              40085
#define ID_SCHEMATYC_GO_BACK            40086
#define ID_SCHEMATYC_GO_TO_AND_FROM_TRANSITION_GRAPH 40087

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        113
#define _APS_NEXT_COMMAND_VALUE         40085
#define _APS_NEXT_CONTROL_VALUE         1079
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
