set(CMAKE_SYSTEM_VERSION 10.0.10586.0)
set(CMAKE_CONFIGURATION_TYPES Debug Profile Release)
set(CMAKE_CONFIGURATION_TYPES "${CMAKE_CONFIGURATION_TYPES}" CACHE STRING "Reset the configurations to what we need" FORCE)

if (CMAKE_CL_64 OR ${CMAKE_GENERATOR} MATCHES "Win64")
	#64bit
	set(BUILD_CPU_ARCHITECTURE x64)
	set(BUILD_PLATFORM Win64)
	set(WIN64 1)
	set(OUTPUT_DIRECTORY_NAME "win_x64")
else()
	#32it
	set(BUILD_CPU_ARCHITECTURE x86)
	set(BUILD_PLATFORM Win32)
	set(OUTPUT_DIRECTORY_NAME "win_x86")
endif()

MESSAGE(STATUS "BUILD_CPU_ARCHITECTURE = ${BUILD_CPU_ARCHITECTURE}" )

include ("${CMAKE_CURRENT_LIST_DIR}/../../CRYENGINE-MSVC.cmake")

add_definitions(-D_WINDOWS -DWIN32 -D_WIN32)

if (BUILD_CPU_ARCHITECTURE STREQUAL x86)
	set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} /arch:SSE2")
	set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /arch:SSE2")
else()
	add_definitions(-D_WIN64)
endif()

