# Copyright 2001-2016 Crytek GmbH / Crytek Group. All rights reserved.

def build(bld):

	bld.CryEngineModule(
		target        = 'CryGameMono',
		vs_filter     = 'Projects/GameMono',
		file_list     = 'gamemono.waf_files',
		pch           = 'StdAfx.cpp',
		includes      = [ '.',  Path('Code/CryEngine/CryAction') ],
		win_lib       = [ 'shell32', 'Gdi32' ],
		durango_lib   = [ 'ws2_32', 'ixmlhttprequest2' ],
	)
