# Copyright 2001-2018 Crytek GmbH / Crytek Group. All rights reserved.
def build(bld):	
	
	bld.CryPluginModule(
		target      = 'MFCToolsPlugin',
		vs_filter	= 'Sandbox/Plugins',
		file_list   = 'MFCToolsPlugin.waf_files',
		pch			= 'StdAfx.cpp',		
		use	= ['EditorCommon'],
		use_module  = [ 'tiff' ],
		module_extensions = ['toolkit_pro'],

		features    = ['qt'],

		defines 	= ['EDITOR_COMMON_IMPORTS'],
		includes    = [ Path('Code/SDKs/squish-ccr')],

		module_provides = dict(
			includes = [ Path('Code/Sandbox/Plugins/MFCToolsPlugin') ]
		),
	)

