# Copyright 2001-2016 Crytek GmbH / Crytek Group. All rights reserved.
def build(bld):	
	
	bld.CryPluginModule(
		target      = 'MFCToolsPlugin',
		vs_filter	= 'Sandbox/Plugins',
		file_list   = 'MFCToolsPlugin.waf_files',
		pch			= 'StdAfx.cpp',
		use	= ['EditorCommon'],
		module_extensions = ['toolkit_pro'],
		defines = ['EDITOR_COMMON_IMPORTS']
	)
