#############################################################################
## Crytek Source File
## Copyright (C) 2015, Crytek Studios
##
## Creator: Paul Slinger
## Date: September 10, 2015
## Description: WAF  based build system
#############################################################################

SUBFOLDERS =	[
	'Impl'
	]
	
def build(bld):
	# Recursive into all sub projects
	bld.recurse(SUBFOLDERS)
	