# Copyright 2001-2016 Crytek GmbH / Crytek Group. All rights reserved.

def build(bld):

	bld.CryEngineModule(
		target      = 'CryPhysics',
		vs_filter   = 'CryEngine',		
		file_list   = 'cryphysics.waf_files',

		pch_debug         = '../StdAfx.cpp',
		pch_profile       = '../StdAfx.cpp',
		
		orbis_cxxflags  = ['-Wno-constant-conversion', '-Wno-null-dereference', '-Wno-array-bounds' ],
	)

	bld.CryResourceCompilerModule(
		target      = 'CryPhysicsRC',
		vs_filter   = 'RC',		
		file_list   = 'cryphysics.waf_files',
		pch         = 'StdAfx.cpp',
	)