# Copyright 2001-2018 Crytek GmbH / Crytek Group. All rights reserved.

def build(bld):
	common_module_provides = dict(
		includes = [ Path('Code/SDKs/libvorbis/include') ]
	)
	# No warnings in 3rdParty code, we can't fix them anyway.
	common_win_cflags = [ '/W0' ]
	common_linux_cflags = [ '-w' ]

	bld.CryEngineStaticModule(
		target    = 'libvorbis',
		vs_filter = 'Libs/Audio',
		file_list = 'libvorbis.waf_files',
		exclude_from_static_code_analyzer = True,

		includes = [ Path('Code/SDKs/libvorbis/include')],
		linux_includes = [ Path('Code/SDKs/libvorbis/lib') ],
		android_includes = [ Path('Code/SDKs/libvorbis/lib') ],

		use_module = ['libogg'],

		win_cflags = common_win_cflags,
		linux_cflags = common_linux_cflags,
		module_provides = common_module_provides
	)

	bld.CryEngineStaticModule( 
		target    = 'libvorbisfile', 
		vs_filter = 'Libs/Audio',
		file_list = 'libvorbisfile.waf_files',
		exclude_from_static_code_analyzer = True,

		includes = [ Path('Code/SDKs/libvorbis/include') ],
		linux_includes = [ Path('Code/SDKs/libvorbis/lib') ],

		use_module = ['libogg', 'libvorbis'],

		win_cflags = common_win_cflags,
		linux_cflags = common_linux_cflags,
		module_provides = common_module_provides
	)
