# Copyright 2001-2019 Crytek GmbH / Crytek Group. All rights reserved.

def build(bld):	
	bld.CryEditorPlugin(
		target = 'EditorBehaviorTree',
		vs_filter = 'Sandbox/Plugins',
		file_list = 'editorbehaviortree.waf_files',
		pch = 'StdAfx.cpp',
		features = 'qt',
		includes = ['.', '..'],
		use=['Editor', 'EditorCommon' ]
	)
