# Copyright 2001-2018 Crytek GmbH / Crytek Group. All rights reserved.

def build(bld):	
	bld.CryEditorPlugin(
		target      = 'EditorEnvironment',
		vs_filter   = 'Sandbox/Plugins',
		file_list   = 'editorenvironment.waf_files',
		pch         = 'stdafx.cpp'
	)

