# Copyright 2001-2018 Crytek GmbH / Crytek Group. All rights reserved.

def build(bld):

	bld.CryEngineModule(
		target     = 'CryAnimation',
		vs_filter  = 'CryEngine',
		file_list  = 'cryanimation.waf_files',

		pch        = 'stdafx.cpp'
	)		
