# Copyright 2001-2019 Crytek GmbH / Crytek Group. All rights reserved.

def build(bld):
	bld.CryEditorPlugin(
		target = 'EditorSchematyc',
		vs_filter = 'Sandbox/Plugins',
		file_list = 'editorplugin.waf_files',
		pch = 'StdAfx.cpp',
		includes = [
			Path('Code/CryEngine/CryAction'),
			Path('Code/CryEngine/CrySchematyc/Core/Interface')
			 ],
		defines = [ 'SCHEMATYC_PLUGIN_EXPORTS' ],
		module_extensions = ['toolkit_pro'],
	)

