# Copyright 2001-2019 Crytek GmbH / Crytek Group. All rights reserved.
	

def build(bld):
	bld.CryEngineModule(
		target     = 'Cry3DEngine',
		vs_filter  = 'CryEngine',		
		file_list  = 'cry3dengine.waf_files',
		use_module = ['lz4', 'mikkelsen'],
		pch        = 'StdAfx.cpp',		
	)	
