# Copyright 2001-2018 Crytek GmbH / Crytek Group. All rights reserved.

def build(bld):	

	bld.CryEngineModule(
		target    = 'CryReflection',
		vs_filter = 'CryEngine',		
		file_list = 'reflection.waf_files',
		pch       = 'StdAfx.cpp'
	)	