// Copyright 2001-2018 Crytek GmbH / Crytek Group. All rights reserved.

#define IDEDIT                                                                               3
#define IDDELETE                                                                             4
#define IDREFRESH                                                                            5
#define IDD_AIANCHORS                                                                        151
#define IDD_AITREEVIEW                                                                       224
#define IDD_AITVMULTIPLE                                                                     225
#define IDD_AISTATEPATTERN                                                                   201
#define IDD_AIMULTIPLESTATES                                                                 200
#define IDD_ITEMDESCRIPTION                                                                  196
#define IDD_ITEMLOCDESC                                                                      226
#define IDD_ITEMTEMPLATELOCDESC                                                              230
#define IDC_ANCHORS                                                                          1401
#define IDC_DESCRIPTION                                                                      1483
#define IDC_NEW                                                                              1539
#define IDC_TREE                                                                             1817
#define IDC_ITEMTEXT                                                                         1951
#define IDC_LISTCAPTION                                                                      1950
#define IDC_LISTBOX                                                                          1969
#define IDC_ITEMEDIT                                                                         1952
#define IDC_LOCATIONEDIT                                                                     1955
#define IDC_SELECTIONLIST                                                                    1967
#define IDC_SELECTIONLIST2                                                                   1968
#define IDC_DESCRIPTIONEDIT                                                                  1752
#define IDC_COMBO1                                                                           1729
#define IDC_POINTER_SO_SELECT                                                                1790
#define IDC_POINTER                                                                          1034
#define ID_SOED_GROUP_BY_NONE                                                                33817
#define ID_SOED_GROUP_BY_OBJECT_CLASS                                                        33818
#define ID_SOED_GROUP_BY_OBJECT_STATE                                                        33819
#define ID_SOED_GROUP_BY_USER_CLASS                                                          33820
#define ID_SOED_GROUP_BY_USER_STATE                                                          33821
#define ID_SOED_GROUP_BY_ACTION                                                              33822
#define ID_SOED_NEW_CONDITION                                                                33823
#define ID_SOED_NEW_CONDITION                                                                33823
#define ID_SOED_CLONE_CONDITION                                                              33825
#define ID_SOED_DELETE_CONDITION                                                             33827
#define ID_SOED_EDIT_CONDITION                                                               33829
#define ID_SOED_HELPERS_EDIT                                                                 33831
#define ID_SOED_HELPERS_NEW                                                                  33833
#define ID_SOED_HELPERS_DELETE                                                               33834
#define ID_SOED_HELPERS_DONE                                                                 33835
#define IDB_HYPERGRAPH_TREE                                                                  431
#define IDB_SOSTATES_TREE                                                                    229
#define IDC_DESCRIPTIONTEXT                                                                  1953
#define IDC_ITEMTEXT2                                                                        1954
#define IDC_ITEMTEXT3                                                                        1957


