# Copyright 2001-2018 Crytek GmbH / Crytek Group. All rights reserved.
def build(bld):	
	
	bld.CryPlugin(
		target      = 'SmartObjectEditorPlugin',
		vs_filter	= 'Sandbox/Plugins',
		file_list   = 'SmartObjectEditorPlugin.waf_files',
		pch			= 'StdAfx.cpp',
		use			= [ 'MFCToolsPlugin', 'Sandbox' ],
		win_module_extensions = ['toolkit_pro'],
		includes	= [ 
			'..',
			Path('Code/Sandbox/EditorQt/Include'),
			Path('Code/Sandbox/EditorQt'),
			Path('Code/Sandbox/Plugins/MFCToolsPlugin')
		]
	)
