# Copyright 2001-2019 Crytek GmbH / Crytek Group. All rights reserved.

def build(bld):	

	bld.CryEngineModule(
		target    = 'CryLiveCreate',
		vs_filter = 'CryEngine',		
		file_list = 'crylivecreate.waf_files',

		pch       = 'StdAfx.cpp',
		includes  = [ '.', '..', Path('Code/CryEngine/CryAction') ],		
	)	