# Copyright 2001-2018 Crytek GmbH / Crytek Group. All rights reserved.

def build(bld):	

	bld.CryEngineStaticModule( 
		target    = 'png16', 
		vs_filter = 'Libs',
		file_list = 'png16.waf_files',
		exclude_from_static_code_analyzer = True,
		
		use_module = ["zlib"],

		win_cflags = ['/w'],
		win_cxxflags = ['/w'],

		durango_cflags = ['/w'],
		durango_cxxflags = ['/w'],
	
		module_provides = dict(
			includes = [ Path('Code/SDKs/png16'), Path('Code/Libs/png16') ],
		),
	)
