# Copyright 2001-2018 Crytek GmbH / Crytek Group. All rights reserved.

def build(bld):

	bld.CryEngineModule(
		target = 'CrySchematyc2',
		vs_filter = 'CryEngine',
		file_list = ['cryschematyc.waf_files', 'baseenv.waf_files'],

		pch = 'StdAfx.cpp',
		defines = 'SCHEMATYC_EXPORTS',
		
		includes = [Path('Code/CryEngine/CryAction') ],

		module_provides = dict(
			defines = [ 'USE_SCHEMATYC_LEGACY_CORE', 'USE_SCHEMATYC_LEGACY_BASE_ENV' ],
		),
		
		#linux_cxxflags = '-fPIC',
	)	
