if(WINDOWS)
	add_library(SDL2 SHARED IMPORTED GLOBAL)
	set_target_properties(SDL2 PROPERTIES IMPORTED_LOCATION "${SDK_DIR}/SDL2/win_x64/bin/SDL2.dll")
	set_target_properties(SDL2 PROPERTIES IMPORTED_IMPLIB "${SDK_DIR}/SDL2/win_x64/lib/SDL2.lib")
	set_target_properties(SDL2 PROPERTIES INTERFACE_INCLUDE_DIRECTORIES "${SDK_DIR}/SDL2/win_x64/include/SDL2")

	deploy_runtime_files("${SDK_DIR}/SDL2/win_x64/bin/SDL2.dll")
elseif(LINUX)
	add_library(SDL2 SHARED IMPORTED GLOBAL)
	set_target_properties(SDL2 PROPERTIES IMPORTED_LOCATION "${SDK_DIR}/SDL2/linux_x64/lib/libSDL2.so")
	set_target_properties(SDL2 PROPERTIES INTERFACE_INCLUDE_DIRECTORIES "${SDK_DIR}/SDL2/linux_x64/include/SDL2")
	set_target_properties(SDL2 PROPERTIES INTERFACE_COMPILE_DEFINITIONS "USE_SDL2")

	deploy_runtime_files("${SDK_DIR}/SDL2/linux_x64/lib/libSDL2*")
elseif(ANDROID)
	add_library(SDL2 SHARED IMPORTED GLOBAL)
	set_target_properties(SDL2 PROPERTIES IMPORTED_LOCATION "${SDK_DIR}/SDL2/android/${CMAKE_ANDROID_ARCH_ABI}/libSDL2.so" )
	set_target_properties(SDL2 PROPERTIES INTERFACE_INCLUDE_DIRECTORIES "${SDK_DIR}/SDL2/android/include" )
	set_target_properties(SDL2 PROPERTIES INTERFACE_COMPILE_DEFINITIONS "USE_SDL2")

	add_library(SDLExt SHARED IMPORTED GLOBAL)
	set_target_properties(SDLExt PROPERTIES IMPORTED_LOCATION "${CRYENGINE_DIR}/Code/Tools/SDLExtension/lib/android-${CMAKE_ANDROID_ARCH_ABI}/libSDL2Ext.so" )
	set_target_properties(SDLExt PROPERTIES INTERFACE_INCLUDE_DIRECTORIES "${CRYENGINE_DIR}/Code/Tools/SDLExtension/src/include" )
	set_target_properties(SDLExt PROPERTIES IMPORTED_NO_SONAME TRUE )
endif()
