if (WINDOWS AND NOT TARGET WinPixEventRuntime)
	if (EXISTS "${SDK_DIR}/winpixeventruntime/")
		add_library(WinPixEventRuntime SHARED IMPORTED GLOBAL)
		target_include_directories(WinPixEventRuntime INTERFACE "${SDK_DIR}/winpixeventruntime/Include")
		set_target_properties(WinPixEventRuntime PROPERTIES IMPORTED_IMPLIB "${SDK_DIR}/winpixeventruntime/bin/WinPixEventRuntime.lib")
		set_target_properties(WinPixEventRuntime PROPERTIES IMPORTED_LOCATION "${SDK_DIR}/winpixeventruntime/bin/WinPixEventRuntime.dll")
		target_compile_definitions(WinPixEventRuntime INTERFACE WIN_PIX_AVAILABLE=1)
		deploy_runtime_files("${SDK_DIR}/winpixeventruntime/bin/WinPixEventRuntime.dll")
	else ()
		add_library(WinPixEventRuntime INTERFACE IMPORTED GLOBAL)
		target_compile_definitions(WinPixEventRuntime INTERFACE WIN_PIX_AVAILABLE=0)
		message("Pix For Windows will not be supported, as the SDK wasn't found at ${SDK_DIR}/winpixeventruntime/")
	endif()
endif()
