# Copyright 2001-2018 Crytek GmbH / Crytek Group. All rights reserved.
def build(bld):	
	
	bld.CryPlugin(
		target      = 'VehicleEditorPlugin',
		vs_filter	= 'Sandbox/Plugins',
		file_list   = 'VehicleEditorPlugin.waf_files',
		pch			= 'StdAfx.cpp',
		use			= [ 'Sandbox', 'MFCToolsPlugin' ],
		module_extensions = ['toolkit_pro'],
		includes	= [	Path('Code/CryEngine/CryAction'), Path('Code/Sandbox/Plugins/MFCToolsPlugin') ]
	)
