# Copyright 2001-2018 Crytek GmbH / Crytek Group. All rights reserved.
def build(bld):	
	
	bld.CryPlugin(
		target      = 'DialogEditorPlugin',
		vs_filter	= 'Sandbox/Plugins',
		file_list   = 'DialogEditorPlugin.waf_files',
		pch			= 'StdAfx.cpp',
		use			= [ 'MFCToolsPlugin' ],
		module_extensions = ['toolkit_pro'],
		includes	= [ Path('Code/Sandbox/Plugins/MFCToolsPlugin'), Path('Code/CryEngine/CryAction')]
	)
