# Copyright 2001-2019 Crytek GmbH / Crytek Group. All rights reserved.
	
def build(bld):	
	bld.CryEditorPlugin(
		target       = 'EditorDynamicResponseSystem',
		vs_filter    = 'Sandbox/Plugins',
		pch          = 'StdAfx.cpp',
		file_list    = 'editordynamicresponsesystem.waf_files',
		includes	= [ Path('Code/Sandbox/Plugins/MFCToolsPlugin')	],
		use			= [ 'MFCToolsPlugin' ]
	)

